### ISSUE TITLE
Image not shown when trying to share your created art to Twitter

### ISSUE THREAD

**Issue by Zeesky-code** [Coskntkk/public-gallery#1]
If you try to share your art to Tweet from the link, you only get the text and not the created art like this: 

![image](https://user-images.githubusercontent.com/71593672/202906549-7a2af55c-a94f-48e7-b67d-1c3af2711c80.png)

**Comment by Coskntkk** [comment]
This problem is because image is stored as buffer in the database and it is not possible to add image from buffer to tweet. Also, this tweet text must have the link of your artwork, so I'm gonna open another issue for that. Thank you so much!
